// Централизованный набор иконок (Lucide).
// Единая точка импорта: позволяет Rollup делать tree-shaking и держать
// в бандле только используемые иконки. Компоненты используют <Icon name="kebab" />.
import {
  Home, BookOpen, Users, Trophy, Radio, MessagesSquare, UserCircle, Bell, Menu,
  LogIn, LogOut, Feather, BookMarked, Search, ChevronRight, ChevronDown, ChevronLeft,
  ChevronUp, ArrowRight, ArrowLeft, ArrowUpRight, ExternalLink, X, Check, CheckCircle,
  User, UserPlus, UserSearch, UserX, UserCog, Settings, Eye, EyeOff, Star, StarOff,
  Heart, MapPin, Crown, Gift, Globe, Calendar, Plus, PenLine, Pencil, PenTool, Image,
  ImageUp, Upload, Download, Save, Trash2, RotateCcw, Reply, CornerDownRight, Send,
  Mail, Paperclip, Unlink, Music, List, ListMusic, Play, Pause, Volume2, Tag, Hash,
  Layers, Filter, SlidersHorizontal, Activity, Compass, Zap, Award, Coins, BadgeCheck,
  Shield, AlertTriangle, Megaphone, Sparkles, Flame, Flag, File, FileText, FileEdit,
  FilePlus, ClipboardCheck, ShoppingCart, MessageSquarePlus, AtSign, CircleUser, Inbox,
} from 'lucide-vue-next';

// kebab-name -> Vue-компонент Lucide
export const iconMap = {
  home: Home,
  'book-open': BookOpen,
  users: Users,
  trophy: Trophy,
  radio: Radio,
  'messages-square': MessagesSquare,
  'user-circle': UserCircle,
  bell: Bell,
  menu: Menu,
  'log-in': LogIn,
  'log-out': LogOut,
  feather: Feather,
  'book-marked': BookMarked,
  search: Search,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  'external-link': ExternalLink,
  x: X,
  check: Check,
  'check-circle': CheckCircle,
  user: User,
  'user-plus': UserPlus,
  'user-search': UserSearch,
  'user-x': UserX,
  'user-cog': UserCog,
  settings: Settings,
  eye: Eye,
  'eye-off': EyeOff,
  star: Star,
  'star-off': StarOff,
  heart: Heart,
  'map-pin': MapPin,
  crown: Crown,
  gift: Gift,
  globe: Globe,
  calendar: Calendar,
  plus: Plus,
  'pen-line': PenLine,
  pencil: Pencil,
  'pen-tool': PenTool,
  image: Image,
  'image-up': ImageUp,
  upload: Upload,
  download: Download,
  save: Save,
  'trash-2': Trash2,
  'rotate-ccw': RotateCcw,
  reply: Reply,
  'corner-down-right': CornerDownRight,
  send: Send,
  mail: Mail,
  paperclip: Paperclip,
  unlink: Unlink,
  music: Music,
  list: List,
  'list-music': ListMusic,
  play: Play,
  pause: Pause,
  'volume-2': Volume2,
  tag: Tag,
  hash: Hash,
  layers: Layers,
  filter: Filter,
  'sliders-horizontal': SlidersHorizontal,
  activity: Activity,
  compass: Compass,
  zap: Zap,
  award: Award,
  coins: Coins,
  'badge-check': BadgeCheck,
  shield: Shield,
  'alert-triangle': AlertTriangle,
  megaphone: Megaphone,
  sparkles: Sparkles,
  flame: Flame,
  flag: Flag,
  file: File,
  'file-text': FileText,
  'file-edit': FileEdit,
  'file-plus': FilePlus,
  'clipboard-check': ClipboardCheck,
  'shopping-cart': ShoppingCart,
  'message-square-plus': MessageSquarePlus,
  'at-sign': AtSign,
  'circle-user': CircleUser,
  inbox: Inbox,
};
